package job

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"

	"github.com/kidsaber/kidsaber-play-api/internal/domain"
	"github.com/kidsaber/kidsaber-play-api/internal/usecase/notify"
	"github.com/kidsaber/kidsaber-play-api/internal/usecase/questions"
)

// Combination represents a single subject × grade × gameType entry.
type Combination struct {
	Subject  domain.Subject
	Grade    int
	GameType domain.GameType
}

// llmGameTypes are the game types pre-generated by the LLM job.
// quick_calculation is always procedural and is excluded.
var llmGameTypes = []domain.GameType{
	domain.GameTypeOptionMultiple,
	domain.GameTypeFillInTheBlanks,
	domain.GameTypeMatching,
}

var subjects = []domain.Subject{
	domain.SubjectMathematics,
	domain.SubjectLanguage,
	domain.SubjectEnglish,
	domain.SubjectScience,
}

// combinations is the full 72-entry matrix: 4 subjects × 6 grades × 3 LLM types.
var combinations []Combination

func init() {
	for _, s := range subjects {
		for grade := 1; grade <= 6; grade++ {
			for _, gt := range llmGameTypes {
				combinations = append(combinations, Combination{Subject: s, Grade: grade, GameType: gt})
			}
		}
	}
}

// Config holds the job configuration.
type Config struct {
	BatchSize         int
	MaxPerCombination int
	SeedIterations    int
	// CombinationDelay is the pause inserted between consecutive LLM calls
	// to stay within the provider's rate limit. Default: 4 s (≤ 15 RPM).
	CombinationDelay  time.Duration
}

// topicPickerI abstracts the TopicPicker for injection.
type topicPickerI interface {
	Pick(subject domain.Subject, grade int, gameType domain.GameType) (string, error)
}

// QuestionGeneratorJob pre-fills the question bank across all 72 subject×grade×type combinations.
// Designed to be triggered externally (e.g. Cloud Scheduler → Cloud Run Job); run once per invocation.
type QuestionGeneratorJob struct {
	generator  questions.QuestionGenerator
	repository questions.QuestionRepository
	jobRepo    questions.JobRunRepository
	notifier   notify.NotificationService
	picker     topicPickerI
	cfg        Config
	logger     *slog.Logger
}

// NewQuestionGeneratorJob creates a QuestionGeneratorJob.
func NewQuestionGeneratorJob(
	generator questions.QuestionGenerator,
	repository questions.QuestionRepository,
	jobRepo questions.JobRunRepository,
	notifier notify.NotificationService,
	picker topicPickerI,
	cfg Config,
	logger *slog.Logger,
) *QuestionGeneratorJob {
	return &QuestionGeneratorJob{
		generator:  generator,
		repository: repository,
		jobRepo:    jobRepo,
		notifier:   notifier,
		picker:     picker,
		cfg:        cfg,
		logger:     logger,
	}
}

// Run executes one full pass over all 72 combinations.
// Returns an error if any combination failed so callers can propagate a non-zero exit code.
func (j *QuestionGeneratorJob) Run(ctx context.Context) error {
	jobRun := &domain.JobRun{
		ID:                uuid.New().String(),
		StartedAt:         time.Now().UTC(),
		Status:            domain.JobStatusRunning,
		CombinationsTotal: len(combinations),
		CreatedAt:         time.Now().UTC(),
	}

	if err := j.jobRepo.Insert(ctx, jobRun); err != nil {
		j.logger.Error("failed to insert job_run", "error", err)
	}

	j.logger.Info("question generator job started",
		"job_run_id", jobRun.ID,
		"combinations", len(combinations))

	var failedDetails []domain.JobErrorDetail

	for i, combo := range combinations {
		if ctx.Err() != nil {
			j.logger.Warn("job context cancelled, stopping early")
			break
		}

		// Throttle between calls to respect the LLM provider's rate limit.
		// Skip the delay before the very first combination.
		if i > 0 && j.cfg.CombinationDelay > 0 {
			select {
			case <-ctx.Done():
				j.logger.Warn("job context cancelled during throttle delay, stopping early")
				break
			case <-time.After(j.cfg.CombinationDelay):
			}
		}
		if ctx.Err() != nil {
			break
		}

		topic, err := j.picker.Pick(combo.Subject, combo.Grade, combo.GameType)
		if err != nil {
			j.logger.Warn("topic picker failed for combination",
				"subject", combo.Subject, "grade", combo.Grade, "type", combo.GameType, "error", err)
			topic = "general"
		}

		generated, genErr := j.generator.Generate(ctx, questions.GenerateParams{
			Subject: combo.Subject,
			Grade:   combo.Grade,
			Type:    combo.GameType,
			Topic:   topic,
			Count:   j.cfg.BatchSize,
		})

		if genErr != nil {
			j.logger.Warn("generation failed for combination",
				"subject", combo.Subject, "grade", combo.Grade, "type", combo.GameType, "error", genErr)
			failedDetails = append(failedDetails, domain.JobErrorDetail{
				Subject: string(combo.Subject),
				Grade:   combo.Grade,
				Type:    string(combo.GameType),
				Error:   genErr.Error(),
			})
			jobRun.CombinationsFailed++
			continue
		}

		insertErr := j.repository.InsertBatch(ctx, generated)
		if insertErr != nil {
			j.logger.Warn("insert failed for combination",
				"subject", combo.Subject, "grade", combo.Grade, "type", combo.GameType, "error", insertErr)
			failedDetails = append(failedDetails, domain.JobErrorDetail{
				Subject: string(combo.Subject),
				Grade:   combo.Grade,
				Type:    string(combo.GameType),
				Error:   fmt.Sprintf("insert failed: %s", insertErr.Error()),
			})
			jobRun.CombinationsFailed++
			continue
		}

		// Insert succeeded — now enforce the cap by deleting most-used excess.
		findParams := questions.FindParams{
			Subject: combo.Subject,
			Grade:   combo.Grade,
			Type:    combo.GameType,
		}

		currentCount, countErr := j.repository.Count(ctx, findParams)
		if countErr == nil {
			excess := currentCount - j.cfg.MaxPerCombination
			if excess > 0 {
				if delErr := j.repository.DeleteMostUsed(ctx, findParams, excess); delErr != nil {
					j.logger.Warn("failed to delete excess questions",
						"subject", combo.Subject, "grade", combo.Grade, "type", combo.GameType, "error", delErr)
				} else {
					jobRun.QuestionsDeleted += excess
				}
			}
		}

		jobRun.CombinationsDone++
		jobRun.QuestionsGenerated += len(generated)
	}

	// Determine final status
	switch {
	case jobRun.CombinationsFailed == 0:
		jobRun.Status = domain.JobStatusSuccess
	case jobRun.CombinationsFailed == len(combinations):
		jobRun.Status = domain.JobStatusFailed
	default:
		jobRun.Status = domain.JobStatusPartial
	}

	now := time.Now().UTC()
	jobRun.FinishedAt = &now
	jobRun.ErrorDetails = failedDetails

	if err := j.jobRepo.Update(ctx, jobRun); err != nil {
		j.logger.Error("failed to update job_run", "error", err, "job_run_id", jobRun.ID)
	}

	j.logger.Info("question generator job finished",
		"job_run_id", jobRun.ID,
		"status", jobRun.Status,
		"combinations_done", jobRun.CombinationsDone,
		"combinations_failed", jobRun.CombinationsFailed,
		"questions_generated", jobRun.QuestionsGenerated,
		"questions_deleted", jobRun.QuestionsDeleted,
	)

	// Notify on any failure
	if jobRun.CombinationsFailed > 0 {
		details := make([]notify.FailureDetail, len(failedDetails))
		for i, d := range failedDetails {
			details[i] = notify.FailureDetail{
				Subject: d.Subject,
				Grade:   d.Grade,
				Type:    d.Type,
				Error:   d.Error,
			}
		}

		event := notify.NotificationEvent{
			Type:        "job_failure",
			JobRunID:    jobRun.ID,
			Status:      string(jobRun.Status),
			FailedCount: jobRun.CombinationsFailed,
			Details:     details,
			Timestamp:   time.Now().UTC(),
		}

		if alertErr := j.notifier.Alert(context.Background(), event); alertErr != nil {
			j.logger.Warn("failed to send job failure notification", "error", alertErr)
		}

		return fmt.Errorf("job completed with %d/%d combinations failed (status: %s)",
			jobRun.CombinationsFailed, len(combinations), jobRun.Status)
	}

	return nil
}
