package domain

import "encoding/json"

// Subject represents an academic subject.
type Subject string

const (
	SubjectMathematics Subject = "mathematics"
	SubjectLanguage    Subject = "language"
	SubjectEnglish     Subject = "english"
	SubjectScience     Subject = "science"
)

// ValidSubjects contains all valid subject values for quick lookup.
var ValidSubjects = map[Subject]bool{
	SubjectMathematics: true,
	SubjectLanguage:    true,
	SubjectEnglish:     true,
	SubjectScience:     true,
}

// GameType represents a game type.
type GameType string

const (
	GameTypeOptionMultiple  GameType = "option_multiple"
	GameTypeFillInTheBlanks GameType = "fill_in_the_blanks"
	GameTypeMatching        GameType = "matching"
	GameTypeQuickCalc       GameType = "quick_calculation"
)

// ValidGameTypes contains all valid game type values.
var ValidGameTypes = map[GameType]bool{
	GameTypeOptionMultiple:  true,
	GameTypeFillInTheBlanks: true,
	GameTypeMatching:        true,
	GameTypeQuickCalc:       true,
}

// LLMGameTypes contains game types served from the DB (pre-generated by LLM).
var LLMGameTypes = map[GameType]bool{
	GameTypeOptionMultiple:  true,
	GameTypeFillInTheBlanks: true,
	GameTypeMatching:        true,
}

// Difficulty represents question difficulty level.
type Difficulty string

const (
	DifficultyEasy   Difficulty = "easy"
	DifficultyMedium Difficulty = "medium"
	DifficultyHard   Difficulty = "hard"
)

// Option represents a selectable answer option.
type Option struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// PairItem represents an item in a matching pair column.
type PairItem struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// Pairs holds the left and right columns for a matching question.
type Pairs struct {
	Left  []PairItem `json:"left"`
	Right []PairItem `json:"right"`
}

// MatchPair represents a single correct pairing in a matching question.
type MatchPair struct {
	LeftID  string `json:"leftId"`
	RightID string `json:"rightId"`
}

// QuestionMeta holds metadata about difficulty and timing.
type QuestionMeta struct {
	Difficulty  Difficulty `json:"difficulty"`
	TimeLimitMs int        `json:"timeLimitMs"`
	Tags        []string   `json:"tags"`
}

// Question represents an educational question.
//
// The CorrectAnswers field varies by game type:
//   - option_multiple / fill_in_the_blanks → JSON array of option ID strings, e.g. ["B"]
//   - quick_calculation                    → JSON array with a single number, e.g. [15]
//   - matching                             → JSON array of {leftId, rightId} objects
//
// Stored as json.RawMessage to preserve exact JSON representation across the DB round-trip.
type Question struct {
	ID             string          `json:"id"`
	Type           GameType        `json:"type"`
	Subject        Subject         `json:"subject"`
	Grade          int             `json:"grade"`
	Topic          string          `json:"topic"`
	Statement      string          `json:"statement"`
	Expression     string          `json:"expression,omitempty"` // quick_calculation only
	Options        []Option        `json:"options,omitempty"`
	Pairs          *Pairs          `json:"pairs,omitempty"`
	CorrectAnswers json.RawMessage `json:"correctAnswers"`
	Meta           QuestionMeta    `json:"meta"`
}
