package domain

// IsValidSubject returns true if the subject value is one of the recognised constants.
func IsValidSubject(s Subject) bool {
	return ValidSubjects[s]
}

// IsValidGameType returns true if the game type value is one of the recognised constants.
func IsValidGameType(g GameType) bool {
	return ValidGameTypes[g]
}

// IsValidGrade returns true if the grade is within the supported range (1–6).
func IsValidGrade(grade int) bool {
	return grade >= 1 && grade <= 6
}

// IsValidCount returns true if the question count is within the supported range (1–30).
func IsValidCount(count int) bool {
	return count >= 1 && count <= 30
}

// IsLLMGameType returns true if the game type is served from the DB (pre-generated by LLM).
// quick_calculation is always procedural and is not an LLM type.
func IsLLMGameType(g GameType) bool {
	return LLMGameTypes[g]
}

// SubjectSpanish returns the Spanish name used in LLM prompts for a given subject.
func SubjectSpanish(s Subject) string {
	switch s {
	case SubjectMathematics:
		return "Matemáticas"
	case SubjectLanguage:
		return "Lengua Castellana y Literatura"
	case SubjectEnglish:
		return "Inglés"
	case SubjectScience:
		return "Conocimiento del Medio Natural, Social y Cultural"
	default:
		return string(s)
	}
}
